# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  roguelike_config = debug
endif
ifeq ($(config),release)
  roguelike_config = release
endif

PROJECTS := roguelike

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

roguelike:
ifneq (,$(roguelike_config))
	@echo "==== Building roguelike ($(roguelike_config)) ===="
	@${MAKE} --no-print-directory -C . -f roguelike.make config=$(roguelike_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f roguelike.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   roguelike"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"